### PR TITLE
Update DG to include manual testing instructions and refactor sequence diagrams

### PR DESCRIPTION
**Pull request by CJerrong**
- Add manual testing instructions for `undo` and `redo` commands
- Refactor sequence diagrams for UndoSequenceDiagram-Logic and UndoSequenceDiagram-Model
- Fix inconsistencies in punctutation of error messages for undo and redo commands, related to issue #133

### CODE REVIEW

**Review by soons1 — COMMENTED** [review]
Documentation looks good, but the error messages for undo and redo lack punctuation, ties in with issue #133

**Comment by CJerrong** [comment]
> Documentation looks good, but the error messages for undo and redo lack punctuation, ties in with issue #133

Oh right good catch, I'll get those punctuation inconsistencies sorted out.

**Review by chaaaaun — APPROVED** [review]
lookin good bro

**Review by gerteck — APPROVED** [review]
LGTM

**Pull request merged**
